[mgr]
cwd = { fg = "#1b7c83" }

find_keyword = { bold = true, fg = "#9a6700" }
find_position = { fg = "#8250df" }

marker_copied = { fg = "#0550ae", bg = "#0550ae" }
marker_cut = { fg = "#bc4c00", bg = "#bc4c00" }
marker_selected = { fg = "#9a6700", bg = "#9a6700" }

count_copied = { fg = "#ffffff", bg = "#0550ae" }
count_cut = { fg = "#ffffff", bg = "#bc4c00" }
count_selected = { fg = "#ffffff", bg = "#9a6700" }

border_style = { fg = "#0969da" }

[tabs]
active = { fg = "#ffffff", bg = "#0969da"}
inactive = { fg = "#0969da", bg = "#f6f8fa" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#0969da", bold = true }
normal_alt = { fg = "#0969da", bg = "#d1d9e0" }

select_alt = { fg = "#8250df", bg = "#d1d9e0" }
select_main = { fg = "#ffffff", bg = "#8250df", bold = true }

unset_main = { fg = "#ffffff", bg = "#bc4c00", bold = true }
unset_alt = { fg = "#bc4c00", bg = "#d1d9e0" }

[status]
perm_exec = { fg = "#0550ae" }
perm_read = { fg = "#9a6700" }
perm_sep = { fg = "#1b7c83" }
perm_type = { fg = "#0969da" }
perm_write = { fg = "#bc4c00" }

progress_error = { fg = "#bc4c00", bg = "#ffffff" }
progress_label = { fg = "#454c54", bg = "#ffffff" }
progress_normal = { fg = "#454c54", bg = "#ffffff" }

[pick]
active = { fg = "#8250df" }
border = { fg = "#0969da" }
inactive = { fg = "#454c54" }

[task]
title = { fg = "#0969da" }
border = { fg = "#0969da" }
hovered = { fg = "#454c54", bg = "#d1d9e0" }

[input]
border = { fg = "#0969da" }
selected = { bg = "#d1d9e0" }

[help]
desc = { fg = "#454c54" }
on = { fg = "#1b7c83" }
run = { fg = "#8250df" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d1d9e0", bg = "#454c54" }

[which]
mask = { bg = "#d1d9e0" }
desc = { fg = "#454c54" }
cand = { fg = "#1b7c83" }
rest = { fg = "#953800" }

separator_style = { fg = "#59636e" }

[notify]
title_info = { fg = "#1b7c83" }
title_warn = { fg = "#9a6700" }
title_error = { fg = "#bc4c00" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1b7c83" },
  { mime = "{audio, video}/*", fg = "#9a6700" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#0550ae" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#0969da" },
  { mime = "*", fg = "#454c54" },
]

