[mgr]
cwd = { fg = "#35a77c" }

find_keyword = { bold = true, fg = "#dfa000" }
find_position = { fg = "#df69ba" }

marker_copied = { fg = "#8da101", bg = "#8da101" }
marker_cut = { fg = "#f85552", bg = "#f85552" }
marker_selected = { fg = "#dfa000", bg = "#dfa000" }

count_copied = { fg = "#fffbef", bg = "#8da101" }
count_cut = { fg = "#fffbef", bg = "#f85552" }
count_selected = { fg = "#fffbef", bg = "#dfa000" }

border_style = { fg = "#3a94c5" }

[tabs]
active = { fg = "#fffbef", bg = "#3a94c5"}
inactive = { fg = "#3a94c5", bg = "#f8f5e4" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#fffbef", bg = "#3a94c5", bold = true }
normal_alt = { fg = "#3a94c5", bg = "#edeada" }

select_alt = { fg = "#df69ba", bg = "#edeada" }
select_main = { fg = "#fffbef", bg = "#df69ba", bold = true }

unset_main = { fg = "#fffbef", bg = "#f85552", bold = true }
unset_alt = { fg = "#f85552", bg = "#edeada" }

[status]
perm_exec = { fg = "#8da101" }
perm_read = { fg = "#dfa000" }
perm_sep = { fg = "#35a77c" }
perm_type = { fg = "#3a94c5" }
perm_write = { fg = "#f85552" }

progress_error = { fg = "#f85552", bg = "#fffbef" }
progress_label = { fg = "#5c6a72", bg = "#fffbef" }
progress_normal = { fg = "#5c6a72", bg = "#fffbef" }

[pick]
active = { fg = "#df69ba" }
border = { fg = "#3a94c5" }
inactive = { fg = "#5c6a72" }

[task]
title = { fg = "#3a94c5" }
border = { fg = "#3a94c5" }
hovered = { fg = "#5c6a72", bg = "#edeada" }

[input]
border = { fg = "#3a94c5" }
selected = { bg = "#edeada" }

[help]
desc = { fg = "#5c6a72" }
on = { fg = "#35a77c" }
run = { fg = "#df69ba" }
hovered = { reversed = true, bold = true }
footer = { fg = "#edeada", bg = "#5c6a72" }

[which]
mask = { bg = "#edeada" }
desc = { fg = "#5c6a72" }
cand = { fg = "#35a77c" }
rest = { fg = "#829181" }

separator_style = { fg = "#829181" }

[notify]
title_info = { fg = "#35a77c" }
title_warn = { fg = "#dfa000" }
title_error = { fg = "#f85552" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#35a77c" },
  { mime = "{audio, video}/*", fg = "#dfa000" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#8da101" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#3a94c5" },
  { mime = "*", fg = "#5c6a72" },
]

