[mgr]
cwd = { fg = "#39c5cf" }

find_keyword = { bold = true, fg = "#d29922" }
find_position = { fg = "#be8fff" }

marker_copied = { fg = "#58a6ff", bg = "#58a6ff" }
marker_cut = { fg = "#f0883e", bg = "#f0883e" }
marker_selected = { fg = "#d29922", bg = "#d29922" }

count_copied = { fg = "#0d1117", bg = "#58a6ff" }
count_cut = { fg = "#0d1117", bg = "#f0883e" }
count_selected = { fg = "#0d1117", bg = "#d29922" }

border_style = { fg = "#58a6ff" }

[tabs]
active = { fg = "#0d1117", bg = "#58a6ff"}
inactive = { fg = "#58a6ff", bg = "#151b23" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#0d1117", bg = "#58a6ff", bold = true }
normal_alt = { fg = "#58a6ff", bg = "#2f3742" }

select_alt = { fg = "#be8fff", bg = "#2f3742" }
select_main = { fg = "#0d1117", bg = "#be8fff", bold = true }

unset_main = { fg = "#0d1117", bg = "#f0883e", bold = true }
unset_alt = { fg = "#f0883e", bg = "#2f3742" }

[status]
perm_exec = { fg = "#58a6ff" }
perm_read = { fg = "#d29922" }
perm_sep = { fg = "#39c5cf" }
perm_type = { fg = "#58a6ff" }
perm_write = { fg = "#f0883e" }

progress_error = { fg = "#f0883e", bg = "#0d1117" }
progress_label = { fg = "#d1d7e0", bg = "#0d1117" }
progress_normal = { fg = "#d1d7e0", bg = "#0d1117" }

[pick]
active = { fg = "#be8fff" }
border = { fg = "#58a6ff" }
inactive = { fg = "#d1d7e0" }

[task]
title = { fg = "#58a6ff" }
border = { fg = "#58a6ff" }
hovered = { fg = "#d1d7e0", bg = "#2f3742" }

[input]
border = { fg = "#58a6ff" }
selected = { bg = "#2f3742" }

[help]
desc = { fg = "#d1d7e0" }
on = { fg = "#39c5cf" }
run = { fg = "#be8fff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2f3742", bg = "#d1d7e0" }

[which]
mask = { bg = "#2f3742" }
desc = { fg = "#d1d7e0" }
cand = { fg = "#39c5cf" }
rest = { fg = "#ffa657" }

separator_style = { fg = "#9198a1" }

[notify]
title_info = { fg = "#39c5cf" }
title_warn = { fg = "#d29922" }
title_error = { fg = "#f0883e" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#39c5cf" },
  { mime = "{audio, video}/*", fg = "#d29922" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#58a6ff" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#58a6ff" },
  { mime = "*", fg = "#d1d7e0" },
]

