[mgr]
cwd = { fg = "#1b7c83" }

find_keyword = { bold = true, fg = "#603700" }
find_position = { fg = "#622cbc" }

marker_copied = { fg = "#024c1a", bg = "#024c1a" }
marker_cut = { fg = "#a0111f", bg = "#a0111f" }
marker_selected = { fg = "#603700", bg = "#603700" }

count_copied = { fg = "#ffffff", bg = "#024c1a" }
count_cut = { fg = "#ffffff", bg = "#a0111f" }
count_selected = { fg = "#ffffff", bg = "#603700" }

border_style = { fg = "#0349b4" }

[tabs]
active = { fg = "#ffffff", bg = "#0349b4"}
inactive = { fg = "#0349b4", bg = "#f6f8fa" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#ffffff", bg = "#0349b4", bold = true }
normal_alt = { fg = "#0349b4", bg = "#d1d9e0" }

select_alt = { fg = "#622cbc", bg = "#d1d9e0" }
select_main = { fg = "#ffffff", bg = "#622cbc", bold = true }

unset_main = { fg = "#ffffff", bg = "#a0111f", bold = true }
unset_alt = { fg = "#a0111f", bg = "#d1d9e0" }

[status]
perm_exec = { fg = "#024c1a" }
perm_read = { fg = "#603700" }
perm_sep = { fg = "#1b7c83" }
perm_type = { fg = "#0349b4" }
perm_write = { fg = "#a0111f" }

progress_error = { fg = "#a0111f", bg = "#ffffff" }
progress_label = { fg = "#454c54", bg = "#ffffff" }
progress_normal = { fg = "#454c54", bg = "#ffffff" }

[pick]
active = { fg = "#622cbc" }
border = { fg = "#0349b4" }
inactive = { fg = "#454c54" }

[task]
title = { fg = "#0349b4" }
border = { fg = "#0349b4" }
hovered = { fg = "#454c54", bg = "#d1d9e0" }

[input]
border = { fg = "#0349b4" }
selected = { bg = "#d1d9e0" }

[help]
desc = { fg = "#454c54" }
on = { fg = "#1b7c83" }
run = { fg = "#622cbc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d1d9e0", bg = "#454c54" }

[which]
mask = { bg = "#d1d9e0" }
desc = { fg = "#454c54" }
cand = { fg = "#1b7c83" }
rest = { fg = "#86061d" }

separator_style = { fg = "#59636e" }

[notify]
title_info = { fg = "#1b7c83" }
title_warn = { fg = "#603700" }
title_error = { fg = "#a0111f" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#1b7c83" },
  { mime = "{audio, video}/*", fg = "#603700" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#024c1a" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#0349b4" },
  { mime = "*", fg = "#454c54" },
]

