[mgr]
cwd = { fg = "#39c5cf" }

find_keyword = { bold = true, fg = "#f0b72f" }
find_position = { fg = "#cb9eff" }

marker_copied = { fg = "#28d751", bg = "#28d751" }
marker_cut = { fg = "#ff9492", bg = "#ff9492" }
marker_selected = { fg = "#f0b72f", bg = "#f0b72f" }

count_copied = { fg = "#0d1117", bg = "#28d751" }
count_cut = { fg = "#0d1117", bg = "#ff9492" }
count_selected = { fg = "#0d1117", bg = "#f0b72f" }

border_style = { fg = "#71b7ff" }

[tabs]
active = { fg = "#0d1117", bg = "#71b7ff"}
inactive = { fg = "#71b7ff", bg = "#151b23" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#0d1117", bg = "#71b7ff", bold = true }
normal_alt = { fg = "#71b7ff", bg = "#2f3742" }

select_alt = { fg = "#cb9eff", bg = "#2f3742" }
select_main = { fg = "#0d1117", bg = "#cb9eff", bold = true }

unset_main = { fg = "#0d1117", bg = "#ff9492", bold = true }
unset_alt = { fg = "#ff9492", bg = "#2f3742" }

[status]
perm_exec = { fg = "#28d751" }
perm_read = { fg = "#f0b72f" }
perm_sep = { fg = "#39c5cf" }
perm_type = { fg = "#71b7ff" }
perm_write = { fg = "#ff9492" }

progress_error = { fg = "#ff9492", bg = "#0d1117" }
progress_label = { fg = "#d1d7e0", bg = "#0d1117" }
progress_normal = { fg = "#d1d7e0", bg = "#0d1117" }

[pick]
active = { fg = "#cb9eff" }
border = { fg = "#71b7ff" }
inactive = { fg = "#d1d7e0" }

[task]
title = { fg = "#71b7ff" }
border = { fg = "#71b7ff" }
hovered = { fg = "#d1d7e0", bg = "#2f3742" }

[input]
border = { fg = "#71b7ff" }
selected = { bg = "#2f3742" }

[help]
desc = { fg = "#d1d7e0" }
on = { fg = "#39c5cf" }
run = { fg = "#cb9eff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2f3742", bg = "#d1d7e0" }

[which]
mask = { bg = "#2f3742" }
desc = { fg = "#d1d7e0" }
cand = { fg = "#39c5cf" }
rest = { fg = "#ffb1af" }

separator_style = { fg = "#9198a1" }

[notify]
title_info = { fg = "#39c5cf" }
title_warn = { fg = "#f0b72f" }
title_error = { fg = "#ff9492" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#39c5cf" },
  { mime = "{audio, video}/*", fg = "#f0b72f" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#28d751" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#71b7ff" },
  { mime = "*", fg = "#d1d7e0" },
]

