[mgr]
cwd = { fg = "#39c5cf" }

find_keyword = { bold = true, fg = "#c69026" }
find_position = { fg = "#b083f0" }

marker_copied = { fg = "#57ab5a", bg = "#57ab5a" }
marker_cut = { fg = "#f47067", bg = "#f47067" }
marker_selected = { fg = "#c69026", bg = "#c69026" }

count_copied = { fg = "#0d1117", bg = "#57ab5a" }
count_cut = { fg = "#0d1117", bg = "#f47067" }
count_selected = { fg = "#0d1117", bg = "#c69026" }

border_style = { fg = "#539bf5" }

[tabs]
active = { fg = "#0d1117", bg = "#539bf5"}
inactive = { fg = "#539bf5", bg = "#151b23" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#0d1117", bg = "#539bf5", bold = true }
normal_alt = { fg = "#539bf5", bg = "#2f3742" }

select_alt = { fg = "#b083f0", bg = "#2f3742" }
select_main = { fg = "#0d1117", bg = "#b083f0", bold = true }

unset_main = { fg = "#0d1117", bg = "#f47067", bold = true }
unset_alt = { fg = "#f47067", bg = "#2f3742" }

[status]
perm_exec = { fg = "#57ab5a" }
perm_read = { fg = "#c69026" }
perm_sep = { fg = "#39c5cf" }
perm_type = { fg = "#539bf5" }
perm_write = { fg = "#f47067" }

progress_error = { fg = "#f47067", bg = "#0d1117" }
progress_label = { fg = "#d1d7e0", bg = "#0d1117" }
progress_normal = { fg = "#d1d7e0", bg = "#0d1117" }

[pick]
active = { fg = "#b083f0" }
border = { fg = "#539bf5" }
inactive = { fg = "#d1d7e0" }

[task]
title = { fg = "#539bf5" }
border = { fg = "#539bf5" }
hovered = { fg = "#d1d7e0", bg = "#2f3742" }

[input]
border = { fg = "#539bf5" }
selected = { bg = "#2f3742" }

[help]
desc = { fg = "#d1d7e0" }
on = { fg = "#39c5cf" }
run = { fg = "#b083f0" }
hovered = { reversed = true, bold = true }
footer = { fg = "#2f3742", bg = "#d1d7e0" }

[which]
mask = { bg = "#2f3742" }
desc = { fg = "#d1d7e0" }
cand = { fg = "#39c5cf" }
rest = { fg = "#ff938a" }

separator_style = { fg = "#9198a1" }

[notify]
title_info = { fg = "#39c5cf" }
title_warn = { fg = "#c69026" }
title_error = { fg = "#f47067" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#39c5cf" },
  { mime = "{audio, video}/*", fg = "#c69026" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#57ab5a" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#539bf5" },
  { mime = "*", fg = "#d1d7e0" },
]

