[mgr]
cwd = { fg = "#00bdc3" }

find_keyword = { bold = true, fg = "#e2bf00" }
find_position = { fg = "#a86bb2" }

marker_copied = { fg = "#4cc300", bg = "#4cc300" }
marker_cut = { fg = "#ff0000", bg = "#ff0000" }
marker_selected = { fg = "#e2bf00", bg = "#e2bf00" }

count_copied = { fg = "#feffff", bg = "#4cc300" }
count_cut = { fg = "#feffff", bg = "#ff0000" }
count_selected = { fg = "#feffff", bg = "#e2bf00" }

border_style = { fg = "#008df5" }

[tabs]
active = { fg = "#feffff", bg = "#008df5"}
inactive = { fg = "#008df5", bg = "#f1f1f1" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#feffff", bg = "#008df5", bold = true }
normal_alt = { fg = "#008df5", bg = "#dcdcdc" }

select_alt = { fg = "#a86bb2", bg = "#dcdcdc" }
select_main = { fg = "#feffff", bg = "#a86bb2", bold = true }

unset_main = { fg = "#feffff", bg = "#ff0000", bold = true }
unset_alt = { fg = "#ff0000", bg = "#dcdcdc" }

[status]
perm_exec = { fg = "#4cc300" }
perm_read = { fg = "#e2bf00" }
perm_sep = { fg = "#00bdc3" }
perm_type = { fg = "#008df5" }
perm_write = { fg = "#ff0000" }

progress_error = { fg = "#ff0000", bg = "#feffff" }
progress_label = { fg = "#4f4f4f", bg = "#feffff" }
progress_normal = { fg = "#4f4f4f", bg = "#feffff" }

[pick]
active = { fg = "#a86bb2" }
border = { fg = "#008df5" }
inactive = { fg = "#4f4f4f" }

[task]
title = { fg = "#008df5" }
border = { fg = "#008df5" }
hovered = { fg = "#4f4f4f", bg = "#dcdcdc" }

[input]
border = { fg = "#008df5" }
selected = { bg = "#dcdcdc" }

[help]
desc = { fg = "#4f4f4f" }
on = { fg = "#00bdc3" }
run = { fg = "#a86bb2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#dcdcdc", bg = "#4f4f4f" }

[which]
mask = { bg = "#dcdcdc" }
desc = { fg = "#4f4f4f" }
cand = { fg = "#00bdc3" }
rest = { fg = "#7f0000" }

separator_style = { fg = "#757575" }

[notify]
title_info = { fg = "#00bdc3" }
title_warn = { fg = "#e2bf00" }
title_error = { fg = "#ff0000" }

[filetype]
rules = [
  { mime = "image/*", fg = "#00bdc3" },
  { mime = "{audio, video}/*", fg = "#e2bf00" },

  { mime = "application/{pdf,doc,rtf}", fg = "#4cc300" },

  { mime = "application/" },

  { url = "*/", fg = "#008df5" },
  { mime = "*", fg = "#4f4f4f" },
]

