[mgr]
cwd = { fg = "#576d82" }

find_keyword = { bold = true, fg = "#6d8257" }
find_position = { fg = "#82576d" }

marker_copied = { fg = "#57826d", bg = "#57826d" }
marker_cut = { fg = "#826d57", bg = "#826d57" }
marker_selected = { fg = "#6d8257", bg = "#6d8257" }

count_copied = { fg = "#dbd6d1", bg = "#57826d" }
count_cut = { fg = "#dbd6d1", bg = "#826d57" }
count_selected = { fg = "#dbd6d1", bg = "#6d8257" }

border_style = { fg = "#6d5782" }

[tabs]
active = { fg = "#dbd6d1", bg = "#6d5782"}
inactive = { fg = "#6d5782", bg = "#beb6ae" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

[mode]
normal_main = { fg = "#dbd6d1", bg = "#6d5782", bold = true }
normal_alt = { fg = "#6d5782", bg = "#a39a90" }

select_alt = { fg = "#82576d", bg = "#a39a90" }
select_main = { fg = "#dbd6d1", bg = "#82576d", bold = true }

unset_main = { fg = "#dbd6d1", bg = "#826d57", bold = true }
unset_alt = { fg = "#826d57", bg = "#a39a90" }

[status]
perm_exec = { fg = "#57826d" }
perm_read = { fg = "#6d8257" }
perm_sep = { fg = "#576d82" }
perm_type = { fg = "#6d5782" }
perm_write = { fg = "#826d57" }

progress_error = { fg = "#826d57", bg = "#dbd6d1" }
progress_label = { fg = "#433b32", bg = "#dbd6d1" }
progress_normal = { fg = "#433b32", bg = "#dbd6d1" }

[pick]
active = { fg = "#82576d" }
border = { fg = "#6d5782" }
inactive = { fg = "#433b32" }

[task]
title = { fg = "#6d5782" }
border = { fg = "#6d5782" }
hovered = { fg = "#433b32", bg = "#a39a90" }

[input]
border = { fg = "#6d5782" }
selected = { bg = "#a39a90" }

[help]
desc = { fg = "#433b32" }
on = { fg = "#576d82" }
run = { fg = "#82576d" }
hovered = { reversed = true, bold = true }
footer = { fg = "#a39a90", bg = "#433b32" }

[which]
mask = { bg = "#a39a90" }
desc = { fg = "#433b32" }
cand = { fg = "#576d82" }
rest = { fg = "#825757" }

separator_style = { fg = "#5a5047" }

[notify]
title_info = { fg = "#576d82" }
title_warn = { fg = "#6d8257" }
title_error = { fg = "#826d57" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#576d82" },
  { mime = "{audio, video}/*", fg = "#6d8257" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#57826d" },
  
  { mime = "application/" },
  
  { url = "*/", fg = "#6d5782" },
  { mime = "*", fg = "#433b32" },
]

